// This code was generated from .proto.ts files.
// Do not edit this file directly if you don't know what you're doing.
// To regenerate this file, run "yarn proto:exportc" in the root directory.

#include <stdint.h>

struct TestPacket {
    uint8_t a;
    uint8_t b;
};
#define ID_TEST_PACKET 1

