// This code was generated from .proto.ts files.
// Do not edit this file directly if you don't know what you're doing.
// To regenerate this file, run "yarn proto:exportc" in the root directory.

#include <stdint.h>

typedef struct {
    uint32_t i;
} TestCanFrame;
#define ID_TEST_CAN_FRAME 224

typedef struct {
    uint32_t x;
    uint32_t y;
} PositionChangeFrame;
#define ID_POSITION_CHANGE_FRAME 3

typedef struct {
} InitBeginFrame;
#define ID_INIT_BEGIN_FRAME 1

typedef struct {
    uint32_t type;
    uint32_t id;
    uint32_t pos_x;
    uint32_t pos_y;
} InitActorFrame;
#define ID_INIT_ACTOR_FRAME 2

typedef struct {
    uint32_t color;
} JunctionChangeFrame;
#define ID_JUNCTION_CHANGE_FRAME 4

typedef struct {
    uint32_t a;
    uint32_t b;
} TestPacket;
#define ID_TEST_PACKET 241